apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mediawiki.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: mediawiki
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/version: {{ .Chart.Version }}
      app.kubernetes.io/part-of: mediawiki
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/part-of: mediawiki
    spec:
      containers:
        - name: {{ .Values.image.mediawiki.container }}
          image: {{ .Values.image.mediawiki.repository }}:{{ .Values.image.mediawiki.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.app.resources | indent 12 }}
          ports:
           - name: app
             containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
            periodSeconds: 30
          env:
{{- range $key, $value := .Values.env }}          #for loop to fetch all env present in vaules.yaml
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
            - name: MEDIAWIKI_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ template "mediawiki.fullname" . }}
                  key: MEDIAWIKI_DB_HOST
            - name: MEDIAWIKI_DB_TYPE
              valueFrom:
                secretKeyRef:
                  name: {{ template "mediawiki.fullname" . }}
                  key: MEDIAWIKI_DB_TYPE
            - name: MEDIAWIKI_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mediawiki.fullname" . }}
                  key: MEDIAWIKI_DB_PASSWORD
            - name: MEDIAWIKI_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "mediawiki.fullname" . }}
                  key: MEDIAWIKI_DB_NAME
            - name: MEDIAWIKI_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "mediawiki.fullname" . }}
                  key: MEDIAWIKI_DB_USER
