apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mediawiki.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  SECRET: aGVsbG8K #dummy secret in base64 encoded
  MEDIAWIKI_DB_HOST: bWVkaWF3aWtpLW15c3FsCg==
  MEDIAWIKI_DB_TYPE: bXlzcWwK
  MEDIAWIKI_DB_PASSWORD: bWVkaWF3aWtpc3VwZXJzZWN1cmUK
  MEDIAWIKI_DB_NAME: bWVkaWF3aWtpCg==
  MEDIAWIKI_DB_USER: bWVkaWF3aWtpCg==
